# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "poetry"
      - run: poetry install

      - name: Lint with pylint
        run: |
          poetry run pylint wbm_newspapers --fail-under=10

      - name: Test with pytest
        run: |
          poetry run pytest
